spring:
  application:
    name: Store_Scheduler_Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler_db
    username: postgres
    password: 1659
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug


jwt:
  # 문/숫자/특수문자 조합 32자 이상
  secret: StoreSchedulerBackendSecretKeyForJwtAuthentication2026!
  # 토큰 만료 시간 (1시간)
  expiration_time: 3600000